"""aiosplus - Modern, asynchronous Python framework for Soroush Plus Bot API."""

from aiosplus.client.session import AioSplusSession
from aiosplus.enums import (
    BotCommandScopeType,
    ChatAction,
    ChatType,
    MaskPoint,
    MessageEntityType,
    ParseMode,
)
from aiosplus.exceptions import (
    NetworkError,
    RestartingUpdateError,
    SoroushAPIError,
    SoroushBadRequest,
    SoroushConflictError,
    SoroushException,
    SoroushFloodError,
    SoroushForbidden,
    SoroushNotFound,
    SoroushServerError,
    SoroushUnauthorized,
)
from aiosplus.types import (
    Animation,
    Audio,
    BotCommand,
    BotCommandScope,
    BotCommandScopeAllPrivateChats,
    BotCommandScopeChat,
    BotCommandScopeDefault,
    CallbackQuery,
    Chat,
    ChatLocation,
    ChatPermissions,
    ChatPhoto,
    Contact,
    Document,
    File,
    ForceReply,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    InputFile,
    InputMedia,
    InputMediaAnimation,
    InputMediaAudio,
    InputMediaDocument,
    InputMediaPhoto,
    InputMediaVideo,
    KeyboardButton,
    Location,
    MaskPosition,
    Message,
    MessageEntity,
    MessageId,
    PhotoSize,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
    ResponseParameters,
    Sticker,
    StickerSet,
    Update,
    User,
    UserProfilePhotos,
    WebhookInfo,
)

__version__ = "0.1.0"
__author__ = "Amin Madani"
__all__ = [
    "__version__",
    "AioSplusSession",
    # Enums
    "ParseMode",
    "ChatType",
    "MessageEntityType",
    "ChatAction",
    "BotCommandScopeType",
    "MaskPoint",
    # Exceptions
    "SoroushException",
    "NetworkError",
    "SoroushAPIError",
    "SoroushBadRequest",
    "SoroushUnauthorized",
    "SoroushForbidden",
    "SoroushNotFound",
    "SoroushConflictError",
    "SoroushFloodError",
    "SoroushServerError",
    "RestartingUpdateError",
    # Types
    "User",
    "Chat",
    "ChatPhoto",
    "ChatPermissions",
    "ChatLocation",
    "Location",
    "PhotoSize",
    "Animation",
    "Audio",
    "Document",
    "Video",
    "VideoNote",
    "Voice",
    "Contact",
    "UserProfilePhotos",
    "File",
    "InputFile",
    "InputMedia",
    "InputMediaPhoto",
    "InputMediaVideo",
    "InputMediaAnimation",
    "InputMediaAudio",
    "InputMediaDocument",
    "InlineKeyboardButton",
    "InlineKeyboardMarkup",
    "KeyboardButton",
    "ReplyKeyboardMarkup",
    "ReplyKeyboardRemove",
    "ForceReply",
    "MessageEntity",
    "MessageId",
    "Message",
    "CallbackQuery",
    "BotCommand",
    "BotCommandScope",
    "BotCommandScopeDefault",
    "BotCommandScopeAllPrivateChats",
    "BotCommandScopeChat",
    "ResponseParameters",
    "WebhookInfo",
    "MaskPosition",
    "Sticker",
    "StickerSet",
    "Update",
]
