"""aiosplus - Modern, asynchronous Python framework for Soroush Plus Bot API."""

from aiosplus.bot.bot import Bot
from aiosplus.client.session import AioSplusSession
from aiosplus.dispatcher.dispatcher import Dispatcher
from aiosplus.dispatcher.event import EventHandler, EventObserver
from aiosplus.dispatcher.router import Router
from aiosplus.enums import (
    BotCommandScopeType,
    ChatAction,
    ChatType,
    MaskPoint,
    MessageEntityType,
    ParseMode,
)
from aiosplus.exceptions import (
    NetworkError,
    RestartingUpdateError,
    SoroushAPIError,
    SoroushBadRequest,
    SoroushConflictError,
    SoroushException,
    SoroushFloodError,
    SoroushForbidden,
    SoroushNotFound,
    SoroushServerError,
    SoroushUnauthorized,
)
from aiosplus.filters import (
    BaseFilter,
    ChatTypeFilter,
    Command,
    CommandObject,
    F,
    MagicFilter,
    StateFilter,
    Text,
)
from aiosplus.fsm.context import FSMContext
from aiosplus.fsm.state import State, StatesGroup
from aiosplus.fsm.storage.base import BaseStorage, StorageKey
from aiosplus.fsm.storage.memory import MemoryStorage
from aiosplus.middlewares.base import BaseMiddleware
from aiosplus.types import (
    Animation,
    Audio,
    BotCommand,
    BotCommandScope,
    BotCommandScopeAllPrivateChats,
    BotCommandScopeChat,
    BotCommandScopeDefault,
    CallbackQuery,
    Chat,
    ChatLocation,
    ChatPermissions,
    ChatPhoto,
    Contact,
    Document,
    File,
    ForceReply,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    InputFile,
    InputMedia,
    InputMediaAnimation,
    InputMediaAudio,
    InputMediaDocument,
    InputMediaPhoto,
    InputMediaVideo,
    KeyboardButton,
    Location,
    MaskPosition,
    Message,
    MessageEntity,
    MessageId,
    PhotoSize,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
    ResponseParameters,
    Sticker,
    StickerSet,
    Update,
    User,
    UserProfilePhotos,
    WebhookInfo,
)
from aiosplus.utils.formatting import (
    blockquote,
    bold,
    code,
    escape_html,
    escape_md,
    italic,
    link,
    pre,
    spoiler,
    strikethrough,
    underline,
)
from aiosplus.utils.keyboard import InlineKeyboardBuilder, ReplyKeyboardBuilder
from aiosplus.utils.webhook import SimpleWebhookHandler

__version__ = "0.1.0"
__author__ = "Amin Madani"
__all__ = [
    "__version__",
    "Bot",
    "AioSplusSession",
    "Dispatcher",
    "Router",
    "EventObserver",
    "EventHandler",
    # FSM
    "State",
    "StatesGroup",
    "FSMContext",
    "BaseStorage",
    "StorageKey",
    "MemoryStorage",
    # Filters
    "BaseFilter",
    "Command",
    "CommandObject",
    "ChatTypeFilter",
    "Text",
    "MagicFilter",
    "StateFilter",
    "F",
    # Middlewares
    "BaseMiddleware",
    # Utilities
    "InlineKeyboardBuilder",
    "ReplyKeyboardBuilder",
    "escape_md",
    "escape_html",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "spoiler",
    "code",
    "pre",
    "link",
    "blockquote",
    "SimpleWebhookHandler",
    # Enums
    "ParseMode",
    "ChatType",
    "MessageEntityType",
    "ChatAction",
    "BotCommandScopeType",
    "MaskPoint",
    # Exceptions
    "SoroushException",
    "NetworkError",
    "SoroushAPIError",
    "SoroushBadRequest",
    "SoroushUnauthorized",
    "SoroushForbidden",
    "SoroushNotFound",
    "SoroushConflictError",
    "SoroushFloodError",
    "SoroushServerError",
    "RestartingUpdateError",
    # Types
    "User",
    "Chat",
    "ChatPhoto",
    "ChatPermissions",
    "ChatLocation",
    "Location",
    "PhotoSize",
    "Animation",
    "Audio",
    "Document",
    "Video",
    "VideoNote",
    "Voice",
    "Contact",
    "UserProfilePhotos",
    "File",
    "InputFile",
    "InputMedia",
    "InputMediaPhoto",
    "InputMediaVideo",
    "InputMediaAnimation",
    "InputMediaAudio",
    "InputMediaDocument",
    "InlineKeyboardButton",
    "InlineKeyboardMarkup",
    "KeyboardButton",
    "ReplyKeyboardMarkup",
    "ReplyKeyboardRemove",
    "ForceReply",
    "MessageEntity",
    "MessageId",
    "Message",
    "CallbackQuery",
    "BotCommand",
    "BotCommandScope",
    "BotCommandScopeDefault",
    "BotCommandScopeAllPrivateChats",
    "BotCommandScopeChat",
    "ResponseParameters",
    "WebhookInfo",
    "MaskPosition",
    "Sticker",
    "StickerSet",
    "Update",
]
